version: "3"

services:
  mariadb:
    build: requirements/mariadb
    container_name: mariadb
    ports:
    - "3306:3306"
    env_file:
      - .env
    restart: always
  nginx:
    build: requirements/nginx
    container_name: nginx
    env_file: 
      - .env
    restart: always 
  wordpress:
    build: requirements/wordpress
    container_name: wordpress
    env_file:
      - .env
    ports:
      - "9000:9000"
    restart: always       