version: '3.7'

services:
    mariadb:
      build: requirements/mariadb
      container_name: mariadb
      image : inception:mariadb
      env_file:
        - .env
      restart: on-failure
      volumes:
        - mariadb_db:/var/lib/mysql/
      networks:
         - np
    nginx:
      build: requirements/nginx
      container_name: nginx
      image: nginx
      env_file: 
        - .env
      ports:
        - "443:443"
      depends_on:
        - wordpress
      restart: on-failure
      volumes:
        - data_wp:/var/www/html/
      networks:
      - np
    wordpress:
      build: requirements/wordpress
      container_name: wordpress
      image: wordpress
      depends_on:
        - mariadb
      env_file:
        - .env
      restart: on-failure
      volumes:
        - data_wp:/var/www/html/
      networks:
        - np
    redis:
      build: requirements/bonus/redis
      container_name: redis
      image: redis
      env_file:
        - .env
      restart: on-failure
      networks:
        - np
    adminer: requirements/bonus/adminer
    container_name: adminer
    image: adminer
    env_file:
      - .env
    ports:
      - "8080:8080"
    restart: on-failure
    networks:
      - np
volumes:
  data_wp:
      driver_opts:
        type: none
        o: bind
        device: /Users/zrabhi/inception_volume/wordpress
  mariadb_db:
      driver_opts:
        type: none
        o: bind
        device: /Users/zrabhi/inception_volume/mariadb

networks:
   np: 
    driver: bridge     