version: "3"

services:
    mariadb:
      build: requirements/mariadb
      container_name: mariadb
      image : mariadb
      expose :
        - "3306"
      env_file:
        - .env
      restart: always
      volumes:
        - mariadb_db:/var/lib/mysql/
      networks:
         - np
    nginx:
      build: requirements/nginx
      container_name: nginx
      image: nginx
      env_file: 
        - .env
      ports:
        - "443:443"
      depends_on:
        - wordpress
      restart: always
      volumes:
        - data_wp:/var/www/html/
      networks:
      - np
    wordpress:
      build: requirements/wordpress
      container_name: wordpress
      image: wordpress
      depends_on:
        - mariadb
      env_file:
        - .env
      expose:
        - "9000"
      restart: always
      volumes:
        - data_wp:/var/www/html/
      networks:
        - np

volumes:
  data_wp:
      driver_opts:
        o: bind
        type: none
        device: /Users/zrabhi/Desktop/inception_volume/wordpress
  mariadb_db:
      driver_opts:
        o: bind
        type: none
        device: /Users/zrabhi/Desktop/inception_volume/mariadb

networks:
   np: 
    driver: bridge    