FROM debian:buster
RUN apt-get update && apt-get upgrade -y && apt-get install curl -y\
    && apt install -y php php-curl php-mysql && apt install -y php7.3-fpm

COPY /tools/script.sh /tmp/script.sh


RUN  chmod +x /tmp/script.sh

ENTRYPOINT [ "sh","/tmp/script.sh" ]

# COPY /tools/wp-config.php /var/www/html/wp-config.php

EXPOSE 9000

CMD ["/bin/bash" ]