FROM debian:buster
RUN apt-get update && apt-get upgrade -y && apt-get install curl -y\
    && apt install -y php php-curl php-mysql && apt install -y php7.3-fpm

COPY /tools/script.sh /tmp/script.sh

RUN  mkdir -p /run/php/ 

RUN  chmod +x /tmp/script.sh

ENTRYPOINT [ "sh","/tmp/script.sh" ] 
# EXPOSE 9000

CMD ["php-fpm7.3", "-F"]