
FROM debian:buster

RUN apt -y update && apt install -y nginx && apt install openssl -y && openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/ssl/private/nginx-selfsigned.key  -out /etc/ssl/certs/nginx-selfsigned.crt -subj="/CN=zrabhi/O=zrabhi.1337.ma/C=MA/L=KHOURIBGA"

COPY ./conf/default /etc/nginx/sites-available/default


CMD [ "nginx", "-g", "daemon off;"]