version: "3"

services:
  mariadb:
    build: mariadb
    container_name: mariadb
    ports:
    - "3306:3306"
    env_file:
      - .env
    restart: always
  nginx:
    build: nginx
    container_name: nginx
    env_file: 
      - .env
    restart: always 